### ISSUE TITLE
Merging of TLS Reporting

### ISSUE THREAD

**Issue by gotspatel** [coax/hmailserver-webadmin#49]
I think you can merge this https://github.com/kimboslice99/hmailserver-webadmin

Regards

EDIT

Also in hMailServer log parser if you can check if the SepSvcLogs=1 in hmailserver.ini (in case the user has opted for separate logging of smtp, imap, pop etc) and parse accordingly

**Comment by coax** [comment]
Merging is no longer possible as v1.7 has breaking changes. I'll take a look at his code and implement into new build if possible.

**Comment by coax** [comment]
Implemented into v1.8, please check it as I do all the changes on live server which doesn't have TLS nor DMARC. Only after it's been tested (both code and UI), I will draft new release. Thanks.

**Comment by coax** [comment]
Added into v1.8 (pre-release): https://github.com/coax/hmailserver-webadmin/commit/3c5eb2b43d6cd18e72d5d08f7164c380b5d80ff9

**Comment by gotspatel** [comment]
working ok but 2 changes in both file required

hm_dmarcreports.php
hm_tlsreports.php

1:  define the _$folder = './logs/dmarc';_ **&** _$folder = './logs/tls';_ respectively globally outside function get_reports() {} (HENCE IT CAN BE USED IN below

2: in dmarc replace this _$files = glob('./dmarcreports/*.xml');_ **with** _$files = glob($folder . '/*.xml');_
3: in tls replace _$files = glob('./tlsreports/*.json');_ **with** _$files = glob($folder . '/*.json');_

and it shows the reports added and old ones correctly


EDIT:

TLS Report Deletion gives on screen error **Permission denied!** 

Since This file is missing  "background_tlsreports.php"

**Comment by coax** [comment]
Should be fixed now in [latest push](https://github.com/coax/hmailserver-webadmin/commit/53e7ecda7ee273455f6cbcd71646de45a793a91b).

**Comment by gotspatel** [comment]
you forgot this file

TLS Report Deletion gives on screen error Permission denied!

Since This file is missing **"background_tlsreports.php"**

**Comment by coax** [comment]
My bad, it's added.

**Comment by gotspatel** [comment]
then it is ready to publish no other errors so far in checking other features
